INFO 10-03 08:12:20 [__init__.py:241] Automatically detected platform cuda.
[1;36m(APIServer pid=2361434)[0;0m INFO 10-03 08:12:25 [api_server.py:1805] vLLM API server version 0.10.1.1
[1;36m(APIServer pid=2361434)[0;0m INFO 10-03 08:12:25 [utils.py:326] non-default args: {'model_tag': 'Qwen/Qwen2.5-7B-Instruct', 'host': '0.0.0.0', 'port': 9303, 'model': 'Qwen/Qwen2.5-7B-Instruct', 'dtype': 'float16', 'max_model_len': 4096, 'tensor_parallel_size': 2, 'gpu_memory_utilization': 0.85}
[1;36m(APIServer pid=2361434)[0;0m INFO 10-03 08:12:37 [__init__.py:711] Resolved architecture: Qwen2ForCausalLM
[1;36m(APIServer pid=2361434)[0;0m WARNING 10-03 08:12:37 [__init__.py:2819] Casting torch.bfloat16 to torch.float16.
[1;36m(APIServer pid=2361434)[0;0m INFO 10-03 08:12:37 [__init__.py:1750] Using max model len 4096
[1;36m(APIServer pid=2361434)[0;0m INFO 10-03 08:12:38 [scheduler.py:222] Chunked prefill is enabled with max_num_batched_tokens=2048.
INFO 10-03 08:12:46 [__init__.py:241] Automatically detected platform cuda.
[1;36m(EngineCore_0 pid=2362212)[0;0m INFO 10-03 08:12:49 [core.py:636] Waiting for init message from front-end.
[1;36m(EngineCore_0 pid=2362212)[0;0m INFO 10-03 08:12:49 [core.py:74] Initializing a V1 LLM engine (v0.10.1.1) with config: model='Qwen/Qwen2.5-7B-Instruct', speculative_config=None, tokenizer='Qwen/Qwen2.5-7B-Instruct', skip_tokenizer_init=False, tokenizer_mode=auto, revision=None, override_neuron_config={}, tokenizer_revision=None, trust_remote_code=False, dtype=torch.float16, max_seq_len=4096, download_dir=None, load_format=auto, tensor_parallel_size=2, pipeline_parallel_size=1, disable_custom_all_reduce=False, quantization=None, enforce_eager=False, kv_cache_dtype=auto, device_config=cuda, decoding_config=DecodingConfig(backend='auto', disable_fallback=False, disable_any_whitespace=False, disable_additional_properties=False, reasoning_backend=''), observability_config=ObservabilityConfig(show_hidden_metrics_for_version=None, otlp_traces_endpoint=None, collect_detailed_traces=None), seed=0, served_model_name=Qwen/Qwen2.5-7B-Instruct, enable_prefix_caching=True, chunked_prefill_enabled=True, use_async_output_proc=True, pooler_config=None, compilation_config={"level":3,"debug_dump_path":"","cache_dir":"","backend":"","custom_ops":[],"splitting_ops":["vllm.unified_attention","vllm.unified_attention_with_output","vllm.mamba_mixer2"],"use_inductor":true,"compile_sizes":[],"inductor_compile_config":{"enable_auto_functionalized_v2":false},"inductor_passes":{},"cudagraph_mode":1,"use_cudagraph":true,"cudagraph_num_of_warmups":1,"cudagraph_capture_sizes":[512,504,496,488,480,472,464,456,448,440,432,424,416,408,400,392,384,376,368,360,352,344,336,328,320,312,304,296,288,280,272,264,256,248,240,232,224,216,208,200,192,184,176,168,160,152,144,136,128,120,112,104,96,88,80,72,64,56,48,40,32,24,16,8,4,2,1],"cudagraph_copy_inputs":false,"full_cuda_graph":false,"pass_config":{},"max_capture_size":512,"local_cache_dir":null}
[1;36m(EngineCore_0 pid=2362212)[0;0m WARNING 10-03 08:12:49 [multiproc_worker_utils.py:273] Reducing Torch parallelism from 12 threads to 1 to avoid unnecessary CPU contention. Set OMP_NUM_THREADS in the external environment to tune this value as needed.
[1;36m(EngineCore_0 pid=2362212)[0;0m INFO 10-03 08:12:49 [shm_broadcast.py:289] vLLM message queue communication handle: Handle(local_reader_ranks=[0, 1], buffer_handle=(2, 16777216, 10, 'psm_1731879c'), local_subscribe_addr='ipc:///tmp/63eaf467-0010-4652-b13f-b747643bd17c', remote_subscribe_addr=None, remote_addr_ipv6=False)
INFO 10-03 08:12:57 [__init__.py:241] Automatically detected platform cuda.
INFO 10-03 08:12:57 [__init__.py:241] Automatically detected platform cuda.
[1;36m(VllmWorker TP1 pid=2362457)[0;0m INFO 10-03 08:13:01 [shm_broadcast.py:289] vLLM message queue communication handle: Handle(local_reader_ranks=[0], buffer_handle=(1, 10485760, 10, 'psm_d42da646'), local_subscribe_addr='ipc:///tmp/89e73582-5c1b-4600-80ef-22835d365cbd', remote_subscribe_addr=None, remote_addr_ipv6=False)
[1;36m(VllmWorker TP0 pid=2362456)[0;0m INFO 10-03 08:13:01 [shm_broadcast.py:289] vLLM message queue communication handle: Handle(local_reader_ranks=[0], buffer_handle=(1, 10485760, 10, 'psm_7d12f544'), local_subscribe_addr='ipc:///tmp/41c2b7ae-d5e8-4c2a-927c-27bd4a44e0dd', remote_subscribe_addr=None, remote_addr_ipv6=False)
[1;36m(VllmWorker TP1 pid=2362457)[0;0m ERROR 10-03 08:13:02 [multiproc_executor.py:559] WorkerProc failed to start.
[1;36m(VllmWorker TP1 pid=2362457)[0;0m ERROR 10-03 08:13:02 [multiproc_executor.py:559] Traceback (most recent call last):
[1;36m(VllmWorker TP1 pid=2362457)[0;0m ERROR 10-03 08:13:02 [multiproc_executor.py:559]   File "/home/mobra/aienv/lib/python3.12/site-packages/vllm/v1/executor/multiproc_executor.py", line 533, in worker_main
[1;36m(VllmWorker TP1 pid=2362457)[0;0m ERROR 10-03 08:13:02 [multiproc_executor.py:559]     worker = WorkerProc(*args, **kwargs)
[1;36m(VllmWorker TP1 pid=2362457)[0;0m ERROR 10-03 08:13:02 [multiproc_executor.py:559]              ^^^^^^^^^^^^^^^^^^^^^^^^^^^
[1;36m(VllmWorker TP1 pid=2362457)[0;0m ERROR 10-03 08:13:02 [multiproc_executor.py:559]   File "/home/mobra/aienv/lib/python3.12/site-packages/vllm/v1/executor/multiproc_executor.py", line 401, in __init__
[1;36m(VllmWorker TP1 pid=2362457)[0;0m ERROR 10-03 08:13:02 [multiproc_executor.py:559]     self.worker.init_device()
[1;36m(VllmWorker TP1 pid=2362457)[0;0m ERROR 10-03 08:13:02 [multiproc_executor.py:559]   File "/home/mobra/aienv/lib/python3.12/site-packages/vllm/worker/worker_base.py", line 603, in init_device
[1;36m(VllmWorker TP1 pid=2362457)[0;0m ERROR 10-03 08:13:02 [multiproc_executor.py:559]     self.worker.init_device()  # type: ignore
[1;36m(VllmWorker TP1 pid=2362457)[0;0m ERROR 10-03 08:13:02 [multiproc_executor.py:559]     ^^^^^^^^^^^^^^^^^^^^^^^^^
[1;36m(VllmWorker TP1 pid=2362457)[0;0m ERROR 10-03 08:13:02 [multiproc_executor.py:559]   File "/home/mobra/aienv/lib/python3.12/site-packages/vllm/v1/worker/gpu_worker.py", line 179, in init_device
[1;36m(VllmWorker TP1 pid=2362457)[0;0m ERROR 10-03 08:13:02 [multiproc_executor.py:559]     raise ValueError(
[1;36m(VllmWorker TP1 pid=2362457)[0;0m ERROR 10-03 08:13:02 [multiproc_executor.py:559] ValueError: Free memory on device (0.24/11.76 GiB) on startup is less than desired GPU memory utilization (0.85, 9.99 GiB). Decrease GPU memory utilization or reduce GPU memory used by other processes.
[1;36m(VllmWorker TP1 pid=2362457)[0;0m INFO 10-03 08:13:02 [multiproc_executor.py:520] Parent process exited, terminating worker
[1;36m(VllmWorker TP0 pid=2362456)[0;0m INFO 10-03 08:13:02 [multiproc_executor.py:520] Parent process exited, terminating worker
[1;36m(EngineCore_0 pid=2362212)[0;0m ERROR 10-03 08:13:05 [core.py:700] EngineCore failed to start.
[1;36m(EngineCore_0 pid=2362212)[0;0m ERROR 10-03 08:13:05 [core.py:700] Traceback (most recent call last):
[1;36m(EngineCore_0 pid=2362212)[0;0m ERROR 10-03 08:13:05 [core.py:700]   File "/home/mobra/aienv/lib/python3.12/site-packages/vllm/v1/engine/core.py", line 691, in run_engine_core
[1;36m(EngineCore_0 pid=2362212)[0;0m ERROR 10-03 08:13:05 [core.py:700]     engine_core = EngineCoreProc(*args, **kwargs)
[1;36m(EngineCore_0 pid=2362212)[0;0m ERROR 10-03 08:13:05 [core.py:700]                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[1;36m(EngineCore_0 pid=2362212)[0;0m ERROR 10-03 08:13:05 [core.py:700]   File "/home/mobra/aienv/lib/python3.12/site-packages/vllm/v1/engine/core.py", line 492, in __init__
[1;36m(EngineCore_0 pid=2362212)[0;0m ERROR 10-03 08:13:05 [core.py:700]     super().__init__(vllm_config, executor_class, log_stats,
[1;36m(EngineCore_0 pid=2362212)[0;0m ERROR 10-03 08:13:05 [core.py:700]   File "/home/mobra/aienv/lib/python3.12/site-packages/vllm/v1/engine/core.py", line 80, in __init__
[1;36m(EngineCore_0 pid=2362212)[0;0m ERROR 10-03 08:13:05 [core.py:700]     self.model_executor = executor_class(vllm_config)
[1;36m(EngineCore_0 pid=2362212)[0;0m ERROR 10-03 08:13:05 [core.py:700]                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
[1;36m(EngineCore_0 pid=2362212)[0;0m ERROR 10-03 08:13:05 [core.py:700]   File "/home/mobra/aienv/lib/python3.12/site-packages/vllm/executor/executor_base.py", line 54, in __init__
[1;36m(EngineCore_0 pid=2362212)[0;0m ERROR 10-03 08:13:05 [core.py:700]     self._init_executor()
[1;36m(EngineCore_0 pid=2362212)[0;0m ERROR 10-03 08:13:05 [core.py:700]   File "/home/mobra/aienv/lib/python3.12/site-packages/vllm/v1/executor/multiproc_executor.py", line 96, in _init_executor
[1;36m(EngineCore_0 pid=2362212)[0;0m ERROR 10-03 08:13:05 [core.py:700]     self.workers = WorkerProc.wait_for_ready(unready_workers)
[1;36m(EngineCore_0 pid=2362212)[0;0m ERROR 10-03 08:13:05 [core.py:700]                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[1;36m(EngineCore_0 pid=2362212)[0;0m ERROR 10-03 08:13:05 [core.py:700]   File "/home/mobra/aienv/lib/python3.12/site-packages/vllm/v1/executor/multiproc_executor.py", line 472, in wait_for_ready
[1;36m(EngineCore_0 pid=2362212)[0;0m ERROR 10-03 08:13:05 [core.py:700]     raise e from None
[1;36m(EngineCore_0 pid=2362212)[0;0m ERROR 10-03 08:13:05 [core.py:700] Exception: WorkerProc initialization failed due to an exception in a background process. See stack trace for root cause.
[1;36m(EngineCore_0 pid=2362212)[0;0m Process EngineCore_0:
[1;36m(EngineCore_0 pid=2362212)[0;0m Traceback (most recent call last):
[1;36m(EngineCore_0 pid=2362212)[0;0m   File "/usr/lib/python3.12/multiprocessing/process.py", line 314, in _bootstrap
[1;36m(EngineCore_0 pid=2362212)[0;0m     self.run()
[1;36m(EngineCore_0 pid=2362212)[0;0m   File "/usr/lib/python3.12/multiprocessing/process.py", line 108, in run
[1;36m(EngineCore_0 pid=2362212)[0;0m     self._target(*self._args, **self._kwargs)
[1;36m(EngineCore_0 pid=2362212)[0;0m   File "/home/mobra/aienv/lib/python3.12/site-packages/vllm/v1/engine/core.py", line 704, in run_engine_core
[1;36m(EngineCore_0 pid=2362212)[0;0m     raise e
[1;36m(EngineCore_0 pid=2362212)[0;0m   File "/home/mobra/aienv/lib/python3.12/site-packages/vllm/v1/engine/core.py", line 691, in run_engine_core
[1;36m(EngineCore_0 pid=2362212)[0;0m     engine_core = EngineCoreProc(*args, **kwargs)
[1;36m(EngineCore_0 pid=2362212)[0;0m                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[1;36m(EngineCore_0 pid=2362212)[0;0m   File "/home/mobra/aienv/lib/python3.12/site-packages/vllm/v1/engine/core.py", line 492, in __init__
[1;36m(EngineCore_0 pid=2362212)[0;0m     super().__init__(vllm_config, executor_class, log_stats,
[1;36m(EngineCore_0 pid=2362212)[0;0m   File "/home/mobra/aienv/lib/python3.12/site-packages/vllm/v1/engine/core.py", line 80, in __init__
[1;36m(EngineCore_0 pid=2362212)[0;0m     self.model_executor = executor_class(vllm_config)
[1;36m(EngineCore_0 pid=2362212)[0;0m                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
[1;36m(EngineCore_0 pid=2362212)[0;0m   File "/home/mobra/aienv/lib/python3.12/site-packages/vllm/executor/executor_base.py", line 54, in __init__
[1;36m(EngineCore_0 pid=2362212)[0;0m     self._init_executor()
[1;36m(EngineCore_0 pid=2362212)[0;0m   File "/home/mobra/aienv/lib/python3.12/site-packages/vllm/v1/executor/multiproc_executor.py", line 96, in _init_executor
[1;36m(EngineCore_0 pid=2362212)[0;0m     self.workers = WorkerProc.wait_for_ready(unready_workers)
[1;36m(EngineCore_0 pid=2362212)[0;0m                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[1;36m(EngineCore_0 pid=2362212)[0;0m   File "/home/mobra/aienv/lib/python3.12/site-packages/vllm/v1/executor/multiproc_executor.py", line 472, in wait_for_ready
[1;36m(EngineCore_0 pid=2362212)[0;0m     raise e from None
[1;36m(EngineCore_0 pid=2362212)[0;0m Exception: WorkerProc initialization failed due to an exception in a background process. See stack trace for root cause.
[1;36m(APIServer pid=2361434)[0;0m Traceback (most recent call last):
[1;36m(APIServer pid=2361434)[0;0m   File "/home/mobra/aienv/bin/vllm", line 7, in <module>
[1;36m(APIServer pid=2361434)[0;0m     sys.exit(main())
[1;36m(APIServer pid=2361434)[0;0m              ^^^^^^
[1;36m(APIServer pid=2361434)[0;0m   File "/home/mobra/aienv/lib/python3.12/site-packages/vllm/entrypoints/cli/main.py", line 54, in main
[1;36m(APIServer pid=2361434)[0;0m     args.dispatch_function(args)
[1;36m(APIServer pid=2361434)[0;0m   File "/home/mobra/aienv/lib/python3.12/site-packages/vllm/entrypoints/cli/serve.py", line 50, in cmd
[1;36m(APIServer pid=2361434)[0;0m     uvloop.run(run_server(args))
[1;36m(APIServer pid=2361434)[0;0m   File "/home/mobra/aienv/lib/python3.12/site-packages/uvloop/__init__.py", line 109, in run
[1;36m(APIServer pid=2361434)[0;0m     return __asyncio.run(
[1;36m(APIServer pid=2361434)[0;0m            ^^^^^^^^^^^^^^
[1;36m(APIServer pid=2361434)[0;0m   File "/usr/lib/python3.12/asyncio/runners.py", line 194, in run
[1;36m(APIServer pid=2361434)[0;0m     return runner.run(main)
[1;36m(APIServer pid=2361434)[0;0m            ^^^^^^^^^^^^^^^^
[1;36m(APIServer pid=2361434)[0;0m   File "/usr/lib/python3.12/asyncio/runners.py", line 118, in run
[1;36m(APIServer pid=2361434)[0;0m     return self._loop.run_until_complete(task)
[1;36m(APIServer pid=2361434)[0;0m            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[1;36m(APIServer pid=2361434)[0;0m   File "uvloop/loop.pyx", line 1518, in uvloop.loop.Loop.run_until_complete
[1;36m(APIServer pid=2361434)[0;0m   File "/home/mobra/aienv/lib/python3.12/site-packages/uvloop/__init__.py", line 61, in wrapper
[1;36m(APIServer pid=2361434)[0;0m     return await main
[1;36m(APIServer pid=2361434)[0;0m            ^^^^^^^^^^
[1;36m(APIServer pid=2361434)[0;0m   File "/home/mobra/aienv/lib/python3.12/site-packages/vllm/entrypoints/openai/api_server.py", line 1850, in run_server
[1;36m(APIServer pid=2361434)[0;0m     await run_server_worker(listen_address, sock, args, **uvicorn_kwargs)
[1;36m(APIServer pid=2361434)[0;0m   File "/home/mobra/aienv/lib/python3.12/site-packages/vllm/entrypoints/openai/api_server.py", line 1870, in run_server_worker
[1;36m(APIServer pid=2361434)[0;0m     async with build_async_engine_client(
[1;36m(APIServer pid=2361434)[0;0m   File "/usr/lib/python3.12/contextlib.py", line 210, in __aenter__
[1;36m(APIServer pid=2361434)[0;0m     return await anext(self.gen)
[1;36m(APIServer pid=2361434)[0;0m            ^^^^^^^^^^^^^^^^^^^^^
[1;36m(APIServer pid=2361434)[0;0m   File "/home/mobra/aienv/lib/python3.12/site-packages/vllm/entrypoints/openai/api_server.py", line 178, in build_async_engine_client
[1;36m(APIServer pid=2361434)[0;0m     async with build_async_engine_client_from_engine_args(
[1;36m(APIServer pid=2361434)[0;0m   File "/usr/lib/python3.12/contextlib.py", line 210, in __aenter__
[1;36m(APIServer pid=2361434)[0;0m     return await anext(self.gen)
[1;36m(APIServer pid=2361434)[0;0m            ^^^^^^^^^^^^^^^^^^^^^
[1;36m(APIServer pid=2361434)[0;0m   File "/home/mobra/aienv/lib/python3.12/site-packages/vllm/entrypoints/openai/api_server.py", line 220, in build_async_engine_client_from_engine_args
[1;36m(APIServer pid=2361434)[0;0m     async_llm = AsyncLLM.from_vllm_config(
[1;36m(APIServer pid=2361434)[0;0m                 ^^^^^^^^^^^^^^^^^^^^^^^^^^
[1;36m(APIServer pid=2361434)[0;0m   File "/home/mobra/aienv/lib/python3.12/site-packages/vllm/utils/__init__.py", line 1557, in inner
[1;36m(APIServer pid=2361434)[0;0m     return fn(*args, **kwargs)
[1;36m(APIServer pid=2361434)[0;0m            ^^^^^^^^^^^^^^^^^^^
[1;36m(APIServer pid=2361434)[0;0m   File "/home/mobra/aienv/lib/python3.12/site-packages/vllm/v1/engine/async_llm.py", line 174, in from_vllm_config
[1;36m(APIServer pid=2361434)[0;0m     return cls(
[1;36m(APIServer pid=2361434)[0;0m            ^^^^
[1;36m(APIServer pid=2361434)[0;0m   File "/home/mobra/aienv/lib/python3.12/site-packages/vllm/v1/engine/async_llm.py", line 120, in __init__
[1;36m(APIServer pid=2361434)[0;0m     self.engine_core = EngineCoreClient.make_async_mp_client(
[1;36m(APIServer pid=2361434)[0;0m                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[1;36m(APIServer pid=2361434)[0;0m   File "/home/mobra/aienv/lib/python3.12/site-packages/vllm/v1/engine/core_client.py", line 102, in make_async_mp_client
[1;36m(APIServer pid=2361434)[0;0m     return AsyncMPClient(*client_args)
[1;36m(APIServer pid=2361434)[0;0m            ^^^^^^^^^^^^^^^^^^^^^^^^^^^
[1;36m(APIServer pid=2361434)[0;0m   File "/home/mobra/aienv/lib/python3.12/site-packages/vllm/v1/engine/core_client.py", line 767, in __init__
[1;36m(APIServer pid=2361434)[0;0m     super().__init__(
[1;36m(APIServer pid=2361434)[0;0m   File "/home/mobra/aienv/lib/python3.12/site-packages/vllm/v1/engine/core_client.py", line 446, in __init__
[1;36m(APIServer pid=2361434)[0;0m     with launch_core_engines(vllm_config, executor_class,
[1;36m(APIServer pid=2361434)[0;0m   File "/usr/lib/python3.12/contextlib.py", line 144, in __exit__
[1;36m(APIServer pid=2361434)[0;0m     next(self.gen)
[1;36m(APIServer pid=2361434)[0;0m   File "/home/mobra/aienv/lib/python3.12/site-packages/vllm/v1/engine/utils.py", line 706, in launch_core_engines
[1;36m(APIServer pid=2361434)[0;0m     wait_for_engine_startup(
[1;36m(APIServer pid=2361434)[0;0m   File "/home/mobra/aienv/lib/python3.12/site-packages/vllm/v1/engine/utils.py", line 759, in wait_for_engine_startup
[1;36m(APIServer pid=2361434)[0;0m     raise RuntimeError("Engine core initialization failed. "
[1;36m(APIServer pid=2361434)[0;0m RuntimeError: Engine core initialization failed. See root cause above. Failed core proc(s): {}
